process for jumbo PR
department-of-veterans-affairs/va.gov-team pull request #12006
Opened 2020-08-04 17:56 UTC by omgitsbillryan

Connects: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11630

2020-08-04 20:02 UTC, rianfowler submitted a review, later dismissed

2020-08-04 20:09 UTC, gunsch reviewed
I'm fine with this policy-wise. Left a number of more editorial suggestions.

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +- I can break my PR up into smaller pieces :point_right: [Break PR Into Smaller Pieces](#break-pr-into-smaller-pieces)
```suggestion
- I can break my PR up into smaller pieces :point_right: [Break PR Into Smaller Pieces](#break-pr-into-smaller-pieces)
- The changed lines of code in my PR is not an accurate measurement how much effort is required to review it 
    - :point_right: [Change How LoC is Calculated](#change-how-loc-is-calculated)
    - :point_right: [Appeal a Jumbo PR Denomination](#appeal-a-jumbo-pr-denomination)
- There is no way my PR can be broken up into smaller pieces :point_right: [File for a Jumbo PR Override](#file-for-a-jumbo-pr-override)
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +- I can break my PR up into smaller pieces :point_right: [Break PR Into Smaller Pieces](#break-pr-into-smaller-pieces)
suggest putting "break up my PR" as the first option ;)

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +You added a large test file (`.csv`) that is no included in the [exclusions list](#jumbo-pr-calculation-rationale)
```suggestion
You added a large test file (`.csv`) that is not included in the [exclusions list](#jumbo-pr-calculation-rationale)
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +1. Open a separate PR that changes how the Danger Bot calculates total LoC
link to where this is done in source?

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +Having > `1000` LoC, doesn't always mean the review will be difficult to review. In his case
```suggestion
Having > `1000` LoC, doesn't always mean the review will be difficult to review. In this case:
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +5. Add a comment in your PR that links to the appeal github issue
```suggestion
2. Use the "Jumbo PR Appeal" GitHub issue template
3. Prefix the title with "Jumbo PR Appeal:"
4. Add the GitHub label "Jumbo PR Appeal"
5. Add a comment in your PR that links to the appeal GitHub issue
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +1. Open a ticket in the `va.gov-team` repo
```suggestion
1. [Open a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) in the `va.gov-team` repo
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +2. The platform team will review that doc (1-2)
```suggestion
2. The platform team will review that doc (1-2 days)
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +3-7 days. This includes
```suggestion
Expect this process to take 3-7 days total. This includes:
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +2. Link back to the jumbo PR in any future smaller chunk PRs
```suggestion
2. Link back to the Jumbo PR in any future smaller chunk PRs
```

2020-08-04 20:09 UTC, gunsch commented on platform/working-with-vsp/jumbo-pull-request.md
> +[screen shot of expanded comment]
```suggestion
We use lines of code (`LoC`) as a measurement for its simplicity & transparency. We ignore a number of files when calculating LoC, such as data files (`.json`, `.csv`), `Gemfile.lock`, and `vcr_cassettes`. See the [`vets-api Dangerfile`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Dangerfile) for the full list of exclusions.

You can expand the comment from the bot to see exactly how your LoC were calculated.
[screen shot of expanded comment]
```

2020-08-07 17:54 UTC, johnpaulashenfelter requested changes
Started a chat with the tech leads -- TL;DR is this is way more process than we need. We're 100% in favor of updating the code review guidelines document with a Q/A about big PRs, and stressing (a) it will be automatically rejected by dangerbot (which is a review), and that (b) you'll need to work with us and it will take a while.

2020-08-07 18:15 UTC, johnpaulashenfelter commented
@omgitsbillryan #12239

2020-08-07 18:18 UTC, omgitsbillryan commented
I agree, this is a bit much for process. It's easy to get carried away when writing this stuff 😜  . My only intent with this PR was to give devs who get blocked by the danger-bot somewhere to go. If that "somewhere to go" is a link to a simple Q/A section of a doc, that's probably better 👍

2020-08-07 18:18 UTC, closed without merging