Update staging-review-processes.md
department-of-veterans-affairs/va.gov-team pull request #16183
Opened 2020-11-13 23:15 UTC by 1Copenut

Work related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/16150:
* "Update docs, and share in ToT, so it's clear that VFS teams need to come to the staging review w/their testing and artifacts complete"

2020-11-16 16:55 UTC, shiragoodman requested changes

2020-11-16 16:55 UTC, shiragoodman commented on platform/accessibility/guidance/staging-review-processes.md
> +Teams must conduct their own accessibility testing **before** scheduling a VSP Collaboration Cycle [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/
Is advanced-accessibility-tests-recommended linked correctly?

2020-11-16 16:55 UTC, shiragoodman commented on platform/accessibility/guidance/staging-review-processes.md
> +If teams have not completed their foundational testing, the VSP accessibility specialist will escalate to DEPO leadership.
recommend changing "the VSP accessibility specialist" to just "VSP"

2020-11-16 17:45 UTC, peggygannon approved these changes
@1Copenut Updates look good to me. Thx!

2020-11-17 16:56 UTC, shiragoodman commented
@1Copenut did you see my requested changes?

2020-11-17 19:41 UTC, shiragoodman approved these changes

2020-11-17 19:58 UTC, merged

2020-11-19 00:26 UTC, rroueche reviewed
Please change VSP to DEPO Platform, and then good to merge!

2020-11-19 14:52 UTC, 1Copenut commented
Done!