Web accessibility testing plan
department-of-veterans-affairs/va.gov-team pull request #23086
Opened 2021-04-12 19:01 UTC by 1Copenut

* Added a web accessibility testing plan modeled after the Mobile team's plan
* Included all of the WCAG2.1 success criteria in a 3-column table to categorize for the VSP Product Support team
* Added a 4-column template for teams to copy/paste and use for their project plans

2021-04-14 18:49 UTC, peggygannon requested changes
HI, @1Copenut I made a few copy edits and committed to your branch.

2021-04-15 16:00 UTC, 1Copenut commented
> HI, @1Copenut I made a few copy edits and committed to your branch.

@peggygannon Thank you! Would you mind updating your changes requested to approved or let me know if I should make additional changes?

2021-04-15 16:08 UTC, peggygannon approved these changes

2021-04-15 16:09 UTC, peggygannon commented
hi, @1Copenut Yes, I just updated to "approved"

2022-11-28 14:53 UTC, closed without merging