Update 508-accessibility-best-practices.md
department-of-veterans-affairs/va.gov-team pull request #2534
Opened 2019-10-17 15:08 UTC by jenstrickland

Supplemented with additional details for testing and tooling; a future iteration will supplement with product strategy, user research, design, and qa best practices.

@1Copenut and @rianfowler — would you please review for accuracy?

2019-10-17 19:10 UTC, rianfowler reviewed
looks good to me but I have to defer to trevor for approval on some of the finer points about testing.

2019-10-18 02:23 UTC, 1Copenut requested changes

2019-10-18 02:23 UTC, 1Copenut commented on platform/accessibility/508-accessibility-best-practices.md
> +- Run the [axe-end to end script with CSV and console output](https://github.com/adhocteam/a11y-snippets/tree/master/test-scripts/axe-e2e) for automated scans of high page count static sites. Errors
Let's remove this bullet point for now. The axe e2e script is way out of date and needs to be brought up to the new version of axe and Chrome Driver.

2019-10-18 02:23 UTC, 1Copenut commented on platform/accessibility/508-accessibility-best-practices.md
> +## Manual Accessibility Testing
The table of contents link at the top of the page needs to be updated so this works properly. The text should match this heading, and the link link will look like this:

```html
[Manual Accessibility Testing](#manual-accessibility-testing)
```

2019-10-23 19:16 UTC, merged

2019-10-23 19:16 UTC, jenstrickland commented
Changes accepted. Thank you!