Create blank-staging-review-feedback
department-of-veterans-affairs/va.gov-team pull request #29055
Opened 2021-08-23 17:01 UTC by allison0034

2021-08-23 19:24 UTC, shiragoodman requested changes

2021-08-23 19:24 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/blank-staging-review-feedback
> +name: Blank Staging Review Feedback Ticket
you can remove "Blank"

2021-08-23 19:24 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/blank-staging-review-feedback
> +### VA.gov Experience Standards
this should be singular - Standard*

2021-08-23 19:24 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/blank-staging-review-feedback
> +- Add labels including appropriate practice area and if it is launch blocking
For labels we should be more specific. Add:

- VFS team label
- VA.gov Experience Standard Issue number (`CCIssueXX.YY`) where XX is the category number and YY is the issue number, per the [VA.gov Experience Standards ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- Practice area labels (`508/accessibility, IA, content, design`) per the [VA.gov Experience Standards ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- 508 defect label, if applicable (`508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4`)
- `launch-blocking` label, if applicable

2021-08-24 15:29 UTC, allison0034 reviewed
Done

2021-08-24 15:29 UTC, merged