Update orientation-epic.md
department-of-veterans-affairs/va.gov-team pull request #35518
Opened 2022-01-18 17:49 UTC by seanasewell

I added role-based orientation Calendly meeting links under "General"

2022-01-18 21:33 UTC, shiragoodman requested changes

2022-01-18 21:33 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/orientation-epic.md
> +- [ ] Schedule Role-based Orientation meeting (schedule via Calendly)
@seanasewell all of the role-based changes are already included in the template but right now they say to "DM" whoever the host is. Can you remove this section and place the links in the appropriate places? I'll comment where they should be.

2022-01-18 21:36 UTC, shiragoodman requested changes

2022-01-18 21:36 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/orientation-epic.md
> +- [ ] Schedule Role-based Orientation meeting (schedule via Calendly)
ok for some reason i can't add comments. However under "### Get set up for your practice area" there are several sections that are organized by role. For example, under "Designers and Researchers" it says to "Request design orientation with @ Allison Christman in Slack." This needs to be replaced with, "Attend Design Orientation meeting (schedule via Calendly)" and link the url. Make sense?

2022-01-18 21:37 UTC, seanasewell commented
@shiragoodman Yes, makes sense. I'll do that now.

2022-01-18 22:01 UTC, seanasewell commented
@shiragoodman Ok, updates made!

2022-01-19 21:53 UTC, shiragoodman approved these changes

2022-01-19 21:54 UTC, shiragoodman commented
looks good @seanasewell !

2022-01-21 15:13 UTC, shiragoodman commented
@seanasewell can you please merge this?

2022-01-21 15:37 UTC, merged

2022-01-21 15:50 UTC, seanasewell commented
@shiragoodman merged!