Update collab-cycle-feedback-staging.md
department-of-veterans-affairs/va.gov-team pull request #47864
Opened 2022-10-05 15:08 UTC by allison0034

2022-10-05 19:08 UTC, CherylEvans approved these changes
@allison0034 All the tasks on the ticket have been addressed in this PR.  Approved. :-)

2022-10-06 15:24 UTC, shiragoodman requested changes

2022-10-06 15:24 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md
> +- If your team has additional questions or needs Platform help validating the issue, please comment in the ticket
can you change this to "comment on the ticket" , not in

2022-10-06 15:24 UTC, shiragoodman commented on .github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md
> +- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your re
I think we should switch lines 62 and 63. I think it makes more sense to warn them of potentially out of scope issues and that it's their responsibility, and THEN say that if they don't believe it's their responsibility to fix, etc.

2022-10-06 16:16 UTC, allison0034 reviewed
Yes!

2022-10-06 16:31 UTC, allison0034 commented
@shiragoodman do you think we need both of these bullets?

- Comment on the ticket if there are questions or concerns

- If a team has additional questions or needs Platform help validating the issue, please comment on the ticket.

2022-10-06 18:30 UTC, shiragoodman commented
@allison0034 yea, you're right. They seem to overlap. I would just stick with the 2nd bullet since it's more descriptive. And then move it to the first bullet slot.

2022-10-10 19:07 UTC, merged