Create Require_MFA_VAgov.md
department-of-veterans-affairs/va.gov-team pull request #58732
Opened 2023-05-19 15:33 UTC by joeniquette

PR which adds a policy for requiring verified mfa accounts for dd changes

2023-05-19 16:01 UTC, asg5704 commented on products/identity/Policies and Procedures/Require_MFA_VAgov.md
> +Fraudulent Direct Deposit account changes on VA.gov are on the rise at VA. In an attempt to reduce fraudulent activity on VA.gov the VA.gov Identity team has implemented a policy that requires all di
> Fraudulent Direct Deposit account changes on VA.gov are on the rise at VA. In an attempt to reduce fraudulent activity on VA.gov the VA.gov Identity team has implemented a policy that requires all direct deposit changes be made by an MFA (multi-factor authentication) required verified ID.me or Login.gov account. This policy was set by the Identity teams PO (Product Owner) at the time the policy was set, Cody Reinold. The policy was set and is not set to expire effective 9/20/2021.

Fraudulent direct deposit account changes on VA.gov are on the rise at the Department of Veterans Affairs. In an attempt to reduce fraudulent activity on VA.gov, the VA.gov Identity team has implemented a policy that requires all direct deposit changes to be made with a verified ID.me or Login.gov account that requires MFA (multi-factor authentication). This policy was set by the Identity team's PO (Product Owner) at the time, Cody Reinold. The policy has been set and is not set to expire until 9/20/2021.

2023-05-19 16:04 UTC, asg5704 commented on products/identity/Policies and Procedures/Require_MFA_VAgov.md
> +All bank account (direct deposit) detail modifications within the VA.gov domain must utilize a multi-factor required verified ID.me or Login.gov account. Services which provide the option to modify b
> utilize a multi-factor required verified ID.me or Login.gov account
utilize verified ID.me or Login.gov accounts with required multi-factor authentication

2023-05-19 16:11 UTC, asg5704 commented on products/identity/Policies and Procedures/Require_MFA_VAgov.md
> +In order to ensure continued access to modify bank account details users which do not currently meet the requirements of a multi-factor required verified ID.me or Login.gov account, the service must
Replace with
In order to ensure continued access to modify bank account details, users who do not currently meet the requirements: 1.) a verified ID.me or Login.gov account AND 2.) multi-factor authentication enabled, must be shown content that explains why their current account does not meet the requirements of VA. The service must also provide the user with a path to meet the VA’s requirements by creating a verified account with ID.me or Login.gov accounts AND setting up the verified account with multi-factor authentication.

2023-05-19 16:13 UTC, asg5704 requested changes
Comments left

2023-05-19 16:18 UTC, bosawt commented on products/identity/Policies and Procedures/Require_MFA_VAgov.md
> +```elixir
elixir?????

2023-05-19 16:22 UTC, asg5704 approved these changes

2023-06-02 15:11 UTC, blacktm approved these changes

2023-06-02 15:15 UTC, merged