Initial sign-in-service client and sts documentation split
department-of-veterans-affairs/va.gov-team pull request #88069
Opened 2024-07-10 20:15 UTC by rileyanderson

Start work on making distinction between Sign-in service `Client Auth` and `Service Account Auth`. 
- Adds new folders:
    - [Sign-In Service/Engineering Docs/Authentication Types/Client Auth (User)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/dfd0fa2cccfcf25248d7273eb7c6c18310b2e61c/products/identity/Products/Sign-In%20Service/Engineering%20Docs/Authentication%20Types/Client%20Auth%20(User))
    - [Sign-In Service/Engineering Docs/Authentication Types/Service Account Auth (STS)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/dfd0fa2cccfcf25248d7273eb7c6c18310b2e61c/products/identity/Products/Sign-In%20Service/Engineering%20Docs/Authentication%20Types/Service%20Account%20Auth%20(STS))
- The existing documentation under `Sign-In Service/Engineering Docs` will eventually be removed. I left it until the `Authentication Types` folder is cleaned up a bit more and external links are updated to new documentation. 
- Created a new postman collection for [Service Account Auth](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/f1c9526e8c04de099832441cd1778bba8a66e213/teams/vsp/teams/Identity/Product%20Documentation/Sign%20In%20Service/postman_collections/Service_Account_Auth.postman_collection.json)
   - collection for Client Auth is WIP
- I want to get this initial update in so I can get the `Service Account Auth` docs and postman collection to a team

2024-07-11 21:13 UTC, joeniquette requested changes
minor change and probably can remove introspect stuff

2024-07-11 21:13 UTC, joeniquette commented on products/identity/Products/Sign-In Service/Engineering Docs/Authentication Types/Client Auth (User)/auth_flows/api_oauth.md
> +#### [Introspect](../endpoints/introspect.md)
I think we deleted this route, we should probably remove the docs for it as well

2024-07-11 21:13 UTC, joeniquette commented on products/identity/Products/Sign-In Service/Engineering Docs/Authentication Types/Client Auth (User)/endpoints/introspect.md
I think we can remove this

2024-07-11 21:13 UTC, joeniquette commented on products/identity/Products/Sign-In Service/Engineering Docs/Authentication Types/Service Account Auth (STS)/postman/postman.md
> +### 5. Make `protected sscoped route` request
```suggestion
### 5. Make `protected scoped route` request
```

2024-07-12 14:18 UTC, bramleyjl reviewed
Looks good, splitting off STS was definitely overdue. Could you please remove the PKCE information from the STS `endpoints/token` document, STS information starts around line 140.

I'll also check out your STS postman collection and work on integrating it into the main Identity Postman collection that we're supporting - I think it makes more sense to maintain one larger collection than multiple individual ones.

2024-07-12 18:39 UTC, merged