Add SLO script doc
department-of-veterans-affairs/va.gov-team pull request #8900
Opened 2020-05-07 20:39 UTC by kfrz

## Background

Update documentation with a brief writeup of how the service-level screenshots were gathered.

2020-05-07 21:35 UTC, alexpappasoddball requested changes
Would like to see a little more of a instruction so that I can give this a try tomorrow and see if I can't get it to run on my machine.  Right now I'm a little lost in where to start.

2020-05-15 15:47 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +- `firefox --version` should be `Mozilla Firefox 72.x` or greater
by default firefox isn't available from commandline

2020-05-15 15:57 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +Find your profile name by opening `about:profiles` in Firefox - the active profile name is what you're looking for.
make it cleare `about:profiles` is in the address bar

2020-05-15 16:02 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +`PROFILE_NAME=$PROFILE ./report-crawler.rb`
mention closing firefox

2020-05-15 16:02 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/report-crawler.rb
> +Selenium::WebDriver::Firefox::Binary.path='/opt/firefox/firefox'
this path needs to be dynamic

2020-05-15 16:42 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/report-crawler.rb
> +Selenium::WebDriver::Firefox::Binary.path='/opt/firefox/firefox'
```
# Selenium::WebDriver::Firefox::Binary.path = '/opt/firefox/firefox'
Selenium::WebDriver::Firefox::Binary.path = '/Applications/Firefox.app/Contents/MacOS/firefox'

default_profile = Selenium::WebDriver::Firefox::Profile.from_name PROFILE_NAME
default_profile.add_extension '/Users/philip/Library/Application Support/Firefox/Profiles/gn6h0ea5.default-release/extensions/switchyomega@feliscatus.addons.mozilla.org.xpi'

options = Selenium::WebDriver::Firefox::Options.new
options.profile = default_profile
driver = Selenium::WebDriver.for :firefox, options: options


# b = Watir::Browser.new :firefox, options: { profile: PROFILE_NAME, log: { level: 'DEBUG' } }, headless: false
b = Watir::Browser.new driver, headless: false
```

2020-05-15 16:43 UTC, erluti commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +- Ensure your browser profile is configured with the [SOCKS5 proxy
mention pngcrush

2020-05-21 18:11 UTC, LindseySaari commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +- `convert --version` should be `Version ImageMagick 6.9.x` or greater [install instructions](https://imagemagick.org/script/download.ph://imagemagick.org/script/download.php)
This link is malformed, looks like it needs to be: https://imagemagick.org/script/download.php

2020-05-21 18:27 UTC, LindseySaari commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +1. Ensure your browser profile is configured to use [SOCKS proxy config](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/scripts/socks/README.md)
[May also want to link to the proxy switcher docs here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f60352f90eaaed4ca4e8539cbf05a81bd519cb31/platform/engineering/internal-tools.md#chrome--firefox)

2020-05-22 18:44 UTC, LindseySaari commented on teams/vsp/teams/tools/backend/external-service-monitoring/README.md
> +- `geckodriver` [install instructions](https://github.com/mozilla/geckodriver/releases)
alternate install option: homebrew

2020-05-26 22:31 UTC, alexpappasoddball approved these changes
LGTM

2020-05-26 23:07 UTC, kfrz commented
Going to merge this as is, understanding there may be some rough edges. The documentation & changelog is up to date and I verified it runs on my machine, at least.

2020-05-26 23:07 UTC, merged