vi-352 Refactor current-clients
department-of-veterans-affairs/va.gov-team pull request #94062
Opened 2024-10-01 19:51 UTC by emilykim13

## Summary
- Refactored `current-clients.md` into separate folders per integration
- [Vi-352](https://jira.devops.va.gov/browse/VI-352)

2024-10-03 15:27 UTC, bramleyjl approved these changes

2024-10-09 19:40 UTC, joeniquette requested changes

2024-10-09 19:40 UTC, joeniquette commented on products/identity/Products/Sign-In Service/Identity Team Integrations/current-clients.md
this is missing the pega, mhv account creation api, arp, and ves integrations. I cant say my list is exhaustive but I have some of them listed in datadog here:
- https://vagov.ddog-gov.com/dashboard/i72-yy8-i97/identity-sts-performance?fromUser=false&refresh_mode=sliding&from_ts=1727897889272&to_ts=1728502689272&live=true
- https://vagov.ddog-gov.com/dashboard/79d-d36-vnf/identity-user-auth-sis-performance?fromUser=false&refresh_mode=sliding&from_ts=1728329892454&to_ts=1728502692454&live=true

2024-10-09 19:53 UTC, joeniquette approved these changes
LGTM...we should have another ticket which updates the pages for those that missing

2024-10-09 19:54 UTC, emilykim13 commented on products/identity/Products/Sign-In Service/Identity Team Integrations/current-clients.md
Oops rerequested review but I just saw this, let me add those

2024-10-09 19:57 UTC, emilykim13 commented on products/identity/Products/Sign-In Service/Identity Team Integrations/current-clients.md
Nvm I will make a new ticket and add more details for the missing integrations, ty!

2024-10-09 20:01 UTC, merged

2024-10-09 20:14 UTC, emilykim13 commented on products/identity/Products/Sign-In Service/Identity Team Integrations/current-clients.md
[New ticket](https://jira.devops.va.gov/browse/VI-629)